### ISSUE TITLE
Markdown File Support

### ISSUE THREAD

**Issue by LuigiZaccagnini** [tuanthanh2067/cv-ssg#17]
Hi tuanthanh2067!

## Feature
I am interested in your project and I would like to add support for Markdown (.md files) in it. 

## Example
If users inputs a text file, nothing will change. If a Markdown file is used as input, only the header one syntax feature will be converted into HTML.  

If you would like this feature please assign me this issue and reply to let me know. Thanks!

**Comment by tuanthanh2067** [comment]
Hello LuigiZaccagnini, 

Unfortunately, I have another partner done that feature. 

Thank you for your interest in my project!
